Handle missing translations (#82)

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -66,6 +66,18 @@ jobs:
     if: needs.changes.outputs.dependabot == 'true'
     uses: ./.github/workflows/dependabot-validate.yml
 
+  translations:
+    runs-on: ubuntu-latest
+    name: Verify translations
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check for missing translations
+        run: |
+          find . -name "*.strings" -exec grep -Hin '= "";' {} \; > $$
+          echo "Found missing translations:"
+          cat $$
+          test -s $$ && exit 1 || true
+
   tests-succeeded:
     name: Tests Succeeded
     needs:
@@ -74,6 +86,7 @@ jobs:
       - editorconfig
       - lane
       - dependabot
+      - translations
 
     runs-on: ubuntu-latest
     steps:
